import "@repo/ui/styles.css"; // <--- includes ui: prefixed tailwind output
import "./globals.css"; // your app-specific styles (no ui: prefix)
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Sidebar } from "@repo/ui/SideBar";
import NavbarClient from "../components/NavbarClient";
import { auth } from "../lib/auth";
import { redirect } from "next/navigation";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  const isAuthenticated = !!session?.user;

  return (
    <html lang="en">
      <body className={`flex min-h-screen bg-gray-100 ${geist.className}`}>
        {isAuthenticated ? (
          <>
            <aside className="w-72">
              <Sidebar />
            </aside>

            <div className="flex-1 flex flex-col">
              <header className="sticky top-0 z-10">
                <NavbarClient />
              </header>

              <main className="p-8">{children}</main>
            </div>
          </>
        ) : (
          // Unauthenticated: center auth pages both vertically and horizontally
          <div className="min-h-screen w-full flex items-center justify-center">
            <main className="w-full max-w-md p-6">{children}</main>
          </div>
        )}
      </body>
    </html>
  );
}